ALTER TABLE daily_revenue 
ADD COLUMN IF NOT EXISTS payment_cash NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bca_kredit_income NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bca_debit_income NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bca_qris_income NUMERIC DEFAULT 0;
