ALTER TABLE daily_revenue 
ADD COLUMN IF NOT EXISTS bca_income NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gobiz_income NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS piutang_gobiz NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS biaya_admin_bank NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS biaya_penjualan_merchant_online NUMERIC DEFAULT 0;
